version: '3'

services: 
  nginx: 
    image: nginx
    container_name: nginx
    ports: 
      - "8080:80"
    command: sh -c "date"

  node1: 
    image: nginx:1.20.1-alpine
    container_name: app1
    ports: 
      - "3000"
    depends_on: 
      - nginx
    volumes: 
      - "./node1/index.html:/usr/share/nginx/html/index.html"

  node2: 
    image: nginx:1.20.1-alpine
    container_name: app2
    ports: 
      - "3000"
    depends_on: 
      - nginx
    volumes: 
      - "./node2/index.html:/usr/share/nginx/html/index.html"